apiVersion: v1
kind: Namespace
metadata:
  name: llm-amd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-0-8b-vllm
  namespace: llm-amd
  labels:
    app: qwen3-0-8b-vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-0-8b-vllm
  template:
    metadata:
      labels:
        app: qwen3-0-8b-vllm
    spec:
      hostIPC: true
      containers:
      - name: vllm
        image: vllm/vllm-openai-rocm:latest
        imagePullPolicy: IfNotPresent
        args:
        - --model
        - Qwen/Qwen3-0.6B
        - --dtype
        - auto
        - --enforce-eager
        - --max-model-len
        - "4096"
        - --disable-frontend-multiprocessing
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: VLLM_ROCM_USE_AITER
          value: "0"
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_PTRACE
          seccompProfile:
            type: Unconfined
        volumeMounts:
        - name: hf-cache
          mountPath: /root/.cache/huggingface
        - name: dev-kfd
          mountPath: /dev/kfd
        - name: dev-dri
          mountPath: /dev/dri
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
      volumes:
      - name: hf-cache
        hostPath:
          path: /var/lib/llm/hf-cache
          type: DirectoryOrCreate
      - name: dev-kfd
        hostPath:
          path: /dev/kfd
          type: CharDevice
      - name: dev-dri
        hostPath:
          path: /dev/dri
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: qwen3-0-8b-vllm
  namespace: llm-amd
spec:
  type: ClusterIP
  selector:
    app: qwen3-0-8b-vllm
  ports:
  - name: http
    port: 8000
    targetPort: 8000
